Remove terraform provider openstack
Because of a build issue unrelated, until I fix it.

```
go: finding github.com/coreos/go-systemd v0.0.0-20190620071333-e64a0ec8b42a

../../../../pkg/mod/github.com/hashicorp/terraform@v0.12.16/backend/remote-state/azure/arm_client.go:83:46: not enough arguments in call to armConfig.GetAuthorizationToken

	have (*adal.OAuthConfig, string)

	want (autorest.Sender, *authentication.OAuthConfig, string)

==> ERROR: A failure occurred in prepare().

    Aborting...
```